### ISSUE TITLE
Improvement pkgconfig libkiwix

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#1117]
Why the naming is different? We have `kiwix` and `libzim`:
```
/usr/local/lib/x86_64-linux-gnu/pkgconfig/kiwix.pc
/usr/local/lib/x86_64-linux-gnu/pkgconfig/libzim.pc
```

It should not be `libkiwix.pc`?

Why we do have `kiwix.pc.in` in our code repo, but nothing similar at libzim level?

**Comment by mgautierfr** [comment]
> Why we do have kiwix.pc.in in our code repo, but nothing similar at libzim level?

Probably because libzim has been update to use the meson module `pkgconfig` and libkiwix is still using the older method of having a template file.

> Why the naming is different? We have kiwix and libzim:

Historical reason. Probably a random guy (me) put this name and we stay with it.
Be careful if you change it. Other project will need to update to search for `libkiwix` instead of `kiwix`.

**Comment by kelson42** [comment]
So we could agree that?
* It should be `libkiwix`
* We should use Meson and remove `kiwix.pc.in`?

**Comment by kelson42** [comment]
@veloman-yunkan I have put this issue as well in the milestone as this can only be done in a major release and the fix seems trivial to me
