### ISSUE TITLE
SECURITY: Public secret for Aria2c RPC command module

### ISSUE THREAD

**Issue by calumapplepie** [kiwix/libkiwix#425]
Simply put, the secret for the aria2 command is in the code, publicly visible (Unless I am mistaken in my C++ reading, and that default is never used).  That means any program capable of sending requests to localhost can order the Aria2 server to do whatever it wants.  That (AFAIK) includes javascript executed by websites, meaning a user with kiwix installed can be made to download arbitrary files just by visiting a website.

The RPC module of Aria2 is complex, and I don't have the time at the moment to examine it in great detail.  While it doesn't permit you to directly run arbitrary commands as download hooks, it is highly complicated and could have an arbitrary code execution issue.  Even if there isn't one, an attacker still has access to a powerful tool, and could probably force all kinds of nasty behaviors.

The fix to this is fairly easy: preprocess the secret in.  If the server is shut down on every update, simply set it to a compile-time random constant,  which would make the attack far harder.  I am not a security person, so I'm no expert on keeping these keys secret, but I do think that it should be at least more than just a string literal.

**Comment by mgautierfr** [comment]
Indeed.
This aria secret is really a small security check.
It could be easily fixed by using a simple random value.

> That (AFAIK) includes javascript executed by websites, meaning a user with kiwix installed can be made to download arbitrary files just by visiting a website.

I'm not sure this attack is possible. The browser should block website trying to do rpc on localhost.
And even if this is possible, it would target only user with kiwix-desktop installed and running.

But I'm not a security export neither and the fix is pretty simple.

**Comment by TheMageKing** [comment]
> Indeed.
> This aria secret is really a small security check.
> It could be easily fixed by using a simple random value.
> 
> > That (AFAIK) includes javascript executed by websites, meaning a user with kiwix installed can be made to download arbitrary files just by visiting a website.
> 
> I'm not sure this attack is possible. The browser should block website trying to do rpc on localhost.
> And even if this is possible, it would target only user with kiwix-desktop installed and running.

I'm not so certain about that: apps (like Zoom, say) appear to be perfectly comfortable interacting with local services.  I'm sure there are safeguards, but I don't know that they are significant enough.

And the fact that it only applies to people with Kiwix installed and running isn't terribly important.  If someone is running Kiwix, they shouldn't be risking their security.

> But I'm not a security export neither and the fix is pretty simple.
Indeed.  I could understand not choosing to generate a random value at compile time, since that would break build reproducibility, and the architecture might make it impossible to just generate and use a different key on every run (I'm not sure how persistent the aria2c server is, compared to the program itself).  But there are other options, and any of them are better than this.

**Comment by kelson42** [comment]
@juuz0 Would you be interested to fix this security issue?

**Comment by juuz0** [comment]
@kelson42 Definitely :+1: Thankyou

**Comment by juuz0** [comment]
@kelson42 Will making the secret a random string work good enough? :)

**Comment by calumapplepie** [comment]
If the string is uniquely generated at each startup and decently long, then it should.
