### ISSUE TITLE
Add favicon to the library page

### ISSUE THREAD

**Issue by mayur-samrutwar** [kiwix/libkiwix#471]
"https://library.kiwix.org/" - This page has no favicon. Adding a favicon will make the page more recognizable and visibly good. I would like to work on this.

**Comment by MananJethwani** [comment]
I guess there is already a ticket for this kiwix/kiwix-tools#159

**Comment by kelson42** [comment]
I will give a feedback but the problem is not that easy. There is a few things first to discuss.

**Comment by kelson42** [comment]
There is two cases:
* We have a content neutral page, like welcome our search result page
* We have a content related page, like an article of Wikipedia.

In the second case it should be the favicon of the content... but otherwise it could be indeed an icon of Kiwix... but actually depending of the OS, we could have multiple favicon (see https://realfavicongenerator.net/favicon_checker).

But we should implement it.

**Comment by mayur-samrutwar** [comment]
> 

The content-related page is embedded inside the kiwix library page. So we can use only one favicon for all the pages. We have to create different-sized favicons for various browsers and platforms.

**Comment by kelson42** [comment]
This is a template, template should be modified to get favicon from zim files.

**Comment by unknownuser2329** [comment]
Is anyone working on this issue? Also, where can I find the favicon image?

**Comment by kelson42** [comment]
@juuz0 Would you be able to implement quicly the Kiwix icon on welcome page? Ticket is pretty old and that should be straight forward to inplement:
* Pick the kiwix icon (in good enough resolution)
* Use https://realfavicongenerator.net/
* Integrate all versions of favicons pictures in soirce code
* Modify Welcom page HTML
,,,,,

**Comment by juuz0** [comment]
@kelson42 👍

**Comment by kelson42** [comment]
Unfortunately this is still or again not OK. Looks at:
![image](https://user-images.githubusercontent.com/1029718/209328177-9edc63f9-b5f6-4bd4-97a3-8085b664054e.png)

@veloman-yunkan Not sure, but it looks like a kind of regression has been added here.

**Comment by veloman-yunkan** [comment]
The Favicon checker "failure" for Android Chrome is caused by [an old known bug in the checker](https://github.com/RealFaviconGenerator/realfavicongenerator/issues/464).

**Comment by veloman-yunkan** [comment]
The issue behind the failure for "Classic, desktop browsers"

> https://library.kiwix.org/skin/favicon/favicon.ico?cacheid=fba03a27 and https://library.kiwix.org/favicon.ico both exist and are different

is more real but of low severity, since though two different files are served at those URLs they are visually similar. https://library.kiwix.org/skin/favicon/favicon.ico?cacheid=fba03a27 is embedded in and served by `kiwix-serve` (with a wrong MIME-type of `text/plain`) whereas https://library.kiwix.org/favicon.ico is a redirection to https://www.kiwix.org/favicon.ico that, to the best of my understanding, is configured in varnish. Should I replace the favicon in `kiwix-serve` with the one at  https://www.kiwix.org/?

**Comment by kelson42** [comment]
@rgaudin I guess Varnish has favicon hardcoded here, can we remove it please and let `kiwix-serve` handle this?
@veloman-yunkan We need to fix the wrong mime-type.

**Comment by rgaudin** [comment]
I removed the redirect. It is now agreed that:

- we change kiwix-serve's embedded version with the one at https://www.kiwix.org/favicon.ico
- we fix the mimetype on the cacheid version
