### ISSUE TITLE
Multizim (suggestions) does not work at all

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#479]
If I search for suggestion in the welcome page, nothing is printed.

I would like to see the results and it would be great to have the logo of the ZIM beside to see in which content the content is available.

See kiwix/kiwix-tools#385 for the fulltext search multizim lack of scalability

**Comment by maneeshpm** [comment]
@kelson42 we can say as a fact that once a Xapian database is ready, search on it is quick(even on huge Xapian DB) and that is something we cannot improve on our side. Now our main concern is *how to make the DB ready first time* and *how to keep it ready for further searches*. 

Answer to *how to keep it ready* is caching, which we have already started looking into in #509

Answering *how to make it ready quickly* is a bit more complicated. Currently in libkiwix side, we make a `zim::Searcher` only after receiving a query(we make it on each query, hence slow). We could prepare a `zim::Searcher` as soon as the user opens a multizim because we can expect them to do at least one search on the zim. 

Now what to do till the `zim::Searcher` is being created? extracting the xapian entry from all the zim in case of multizim takes time. We could show a message "Searcher is preparing" and offer a simpler/stripped down search using zim index which is quick till the searcher is ready.

**Comment by kelson42** [comment]
The topic of the cold start is already touched in https://github.com/openzim/libzim/issues/418. I would keep this topic outside this ticket. That said I still believe that if kiwix-serve has 2000 zim files open, then a multizim search won't give an answer in a reasonable time and memory consumption. This is IMO mostly what this ticket is about.

**Comment by kelson42** [comment]
Here is how I would propose to proceed. First of all this is a quite lartge ticket, so I would first propose to split it in following tasks:
* Multizim search ABI design should be agreed/confirmed, automated tests should be written to test it.
* High load situation should be discussed and a solution should be provided to (1) allow users to get proper feedback in reasonable amount of time (2) avoid the whole software to crash/timeout because of lack of CPU/memory.
* Kiwix-serve Multizim REST API design should be adapted/checked/tested.
* Kiwix-serve multizim search should be re-introduced (it was the default on the welcome page taskbar, but since a few weeks we don't have a taskbar anymore on the welcome page... this was not working most of the time anyway).

@maneeshpm @mgautierfr Do you agree? Have you comments?

**Comment by kelson42** [comment]
@maneeshpm Would you mine to tackle the multizim problem until we fix the last details of #509?

**Comment by kelson42** [comment]
@maneeshpm Any thoughts about the plan? Would you be ready to implement it?

**Comment by kelson42** [comment]
@maneeshpm We need to move quickly now an this. Therfore, I have reassigned the ticket to @mgautierfr. Hope this is OK for you?

**Comment by kelson42** [comment]
Fulltext multizim search is fixed with #731. The multizim suggestion work is left to do.

**Comment by kelson42** [comment]
I guess this is ticket fot openzim/linbzim meanwhile.

We should fix https://github.com/openzim/libzim/issues/734 forst IMO.

**Comment by kelson42** [comment]
Moving to `openzim/libzim` where it belongs.

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/libzim](https://github.com/openzim/libzim/issues/932)
