### ISSUE TITLE
handle-search is getting stuck when using "containing..."

### ISSUE THREAD

**Issue by MarkA80** [kiwix/libkiwix#515]
Hi,
I am using wiki-serve 3.1.2-4 for windows with the latest .zim.

When using the search bar and selecting "containing..." 
Doing the verbose, it gets stuck on the handle search.
Is it possible to disable this feature with a start option!
The normal search where the suggestions are popping up is working.

I tried out the kiwix reader on mac and it seems to have a similar issue when doing several searches, that it crashes.
The plugin for the webbrowser seems to be fine.

My work around is to stop the process every 30 seconds and restart it.

**Comment by mgautierfr** [comment]
After investigation, there are several points :

The bug should appears with libzim 6.3.0 AND zim file using zstd compression.
We are compressing our content with level 22, which imply a windows (to search occurrences) of (1^27 Bytes, 128Mb). So at decompression level, we need to allocate such memory.
On top of that, libzim 6.3.0 do partial decompression. We do not decompress all the cluster but just enough to get the wanted blob. To avoid decompress several time the same value, we keep in cache the decompression context and so we keep alive a 128Mb buffer per clusters.

With a default cache of 16 cluster, this means we allocate 2Gb.
On linux, lazy allocation is made, the 2Gb are not really allocated and we really use want needed (the clusters are about 1Mb by default, so a total of around 16Mb).
But on windows, this is real allocation and we run out of memory (on top of the 2Gb, we need 128Mb of continuous memory).
If you add a bug in libzim itself where we are not checking return value of the decompression step in a loop, we have this bug, we are stuck in a infinite loop.

What to do :
- Fix the decompression loop to detect the problem. At least we will have a 500 error code on kiwix-serve and not a infinite loop. (But it will not reduce the memory usage)
- Compress less our content. Level 19 need a 8Mb buffer for almost the same compression ratio.

A workaround for this bug is to reduce the cluster cache size by setting the env variable `ZIM_CLUSTERCACHE`. (ZIM_CLUSTERCACHE=2)

**Comment by kelson42** [comment]
Ping @veloman-yunkan in case you miss this discussion.

**Comment by kelson42** [comment]
@mgautierfr Thank you for the investigation and the analysis. Your two proposal look good to me. This should be quickly implemented and one time merged, we should backport them and release a libzim 6.3.1. We should as well quickly if this resolve as well #513

**Comment by kelson42** [comment]
@mgautierfr With the fix how many zim can beliaded in parallel in a RPI W Zero?

**Comment by mgautierfr** [comment]
Please test with binaries in http://tmp.kiwix.org/kiwix-tools_3.1.2-5/

**Comment by kelson42** [comment]
@jamalex @MarkA80 @OscarL  Let us know quickly - if possible - about the result of your test. We would like to make a new release only with this fix.

**Comment by jamalex** [comment]
I can confirm that `kiwix-tools_win-i686-3.1.2-5-rc1/kiwix-serve.exe` responds quickly and reliably, when I try it with the case I mentioned above that was previously hanging.

**Comment by kelson42** [comment]
@jamalex Thank you for testing again. An official new maintenance release of kiwix-tools will be done in the next days. Closing the ticket.

**Comment by OscarL** [comment]
@kelson42: Just to add another data point (sorry for not replying sooner)... With the test binaries (from `kiwix-tools_win-i686-3.1.2-5-rc1.zip`), search using "contains..." works without getting stuck! Which means I'm now able to use this version (with newer .zim files!).

Thanks to all of you for your work. It is appreciated!
