### ISSUE TITLE
Implement opensearch backend to kiwix-serve

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#586]
_From @kelson42 on September 5, 2016 18:11_

For ideascube, but not only, it would be good to provide an opensearch backend with at least following properties:
Allow to search against all indexes (or only a selection of them)
At least json output (http://www.opensearch.org/Community/JSON_Formats)

_Copied from original issue: kiwix/kiwix-xulrunner#307_

**Comment by kelson42** [comment]
@MananJethwani I think, once the multizim works, this would be the ultimate ticket to implement.

**Comment by fheslouin** [comment]
For the record, the PR that was suggested for OLIP back then : https://github.com/kiwix/libkiwix/pull/295

**Comment by barbayellow** [comment]
Hello, we discussed about the search with some OLIP users. Since there might be several applications installed on OLIP, kiwix, kolibri, BSF mediacenter, Moodle etc. the user should be able to see only x results per application. The search should be as fast as possible and usually no one go beyond the first 10 results. 

An open question: should we allow the user to choose a specific language for the search? That could also drastically improve the speed search. However, this mean that every content in OLIP should expose its main language.
