### ISSUE TITLE
Fix test (if accurate) after change in libzim getTitle.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#592]
The last Pr in libzim (openzim/libzim#586) make the function `getTitle` return case sensitive title.
The unit test on libkiwix side must be corrected.
Please check first this is the real cause and not a introduced bug.

See https://github.com/kiwix/kiwix-build/pull/494/checks?check_run_id=3172877949

**Comment by maneeshpm** [comment]
@mgautierfr  According to the test report, the failed CI is due to a failed unit test on libzim side. 
see https://github.com/kiwix/kiwix-build/runs/3172877949?check_suite_focus=true#step:6:208

It's a bit strange since even on the newer PRs on both libzim and libkiwix all the CI are passing. We have to confirm if this issue is specifically with kiwix-build(specifically on that build system).

**Comment by kelson42** [comment]
@mgautierfr @maneeshpm So, this ticket should but just closed as invalid? I don't really understand what is expected here and why kiwix-build plays a role.

**Comment by maneeshpm** [comment]
I suspected kiwix-build because we have all tests in the newer PRs in both libzim and libkiwix passing, that (might) rule out the possibility of anything wrong with our libraries and this might be just an isolated incident.

**Comment by kelson42** [comment]
@mgautierfr We need your feedback here, not clear at all where this ticket is going.

**Comment by mgautierfr** [comment]
I don't know what happen here. Both CI in libkiwix/libzim are ok, and kiwix-build CI is passing.

I'm closing. I will reopen it if something goes wrong again.
