### ISSUE TITLE
Fournish HTTP URL helper for the server

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#613]
Kiwix Serve, Kiwix Desktop and Kiwix for Android provide a HTTP daemon feature based on the libkiwix server primitive.

In an attempt ot increase usability Kiwix Desktop and Kiwix for Android provide a `http://192.158.1.42:80/` like of URL the software user can easy share with a broader audience connected to the same local (WiFi) network. This is handy and we want a similar feature  for Kiwix Serve as well, see https://github.com/kiwix/kiwix-tools/issues/473.

For the moment Kiwix Desktop and Kiwix Android have each their own implementation to figure out this HTTP URL, but to avoid to code for a third time such a primitive in Kiwix Serve. I would like to have in libkiwix and would basically be:
* List all interfaces/IPs
* Choose the best IP (heuristic) if not specified
* Build URL (with the port).

We had an implementation in Kiwix Desktop 1.0 which seems a good start point:
https://github.com/kiwix/kiwix-xulrunner/blob/master/src/common/networkTools.cpp

Does not handle IPV5 though... but not sure this is really necessary in a LAN context.

**Comment by mgautierfr** [comment]
On the server side, if the address is not specified (which is the case) we are listening to all interfaces. So any (existing) IP is a "valid" ip for the user.
We probably don't want to display localhost (127.0.0.1) to the user (as it would be useless to share) and we **may** also discard public IP (user should not have them, and if they do, they probably know what they are doing).

---

> Does not handle IPV5 though... but not sure this is really necessary in a LAN context.

IPV5 definitively not 😄 

But IPV6 is a open question.
We (all of us) are still using ipv4 because of softwares not handling ipv6, it may be time to handle it.
In the same time we are listening to all ipv4 address, not ipv6 so displaying a ipv6 is also useless.

**Comment by juuz0** [comment]
Would like to give it a try if someone isnt working on this.

**Comment by kelson42** [comment]
@juuz0 yes, thank you.

**Comment by kelson42** [comment]
@juuz0 Any problem with this ticket?

**Comment by juuz0** [comment]
@kelson42 Yeah, I got totally stuck in how to approach this. 
Since I've a holiday today, will try again! :D

**Comment by juuz0** [comment]
@kelson42 
So, we should list all IPs and ask the user which one they would like to use? 
and if they choose none, we give the best one ourselves, am I thinking it right?

Also, are we going ahead with ipv4 only?

**Comment by kelson42** [comment]
@juuz0 Yes, I would recommend to start with ibpv4 first,  ut yes ultimatively woukd be good to support ipv6 as well.

**Comment by juuz0** [comment]
I'm running into an issue. 

If I call any function which returns `std::string` from `InternalServer::start`, it throws  something like -
`undefined reference to functionName[abi:cxx11]()`

I searched around and everywhere it seems to suggest to use some flag (`-D_GLIBCXX_USE_CXX11_ABI=0`) but that probably isn't the right way. What could be wrong ?

Enviroment - 
Ubuntu 21.04
GCC 10.3.0
