### ISSUE TITLE
Make many useless methods deprecated

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#654]
With libzim7 and libkiwix10 we have moved a bit of logic to libzim. Libkiwix to a certain extend is simpler and now many metods are simple wrappers over one libzim method. Beside keeping API compatibility, this as no value and ultimatively such methods will disappear. The sooner the better. We should mark these methods as deprecated and print warnings if they are used to inform users and push developers to update their code.

**Comment by kelson42** [comment]
@veloman-yunkan Would you be able to implement this please?

**Comment by veloman-yunkan** [comment]
> and print warnings if they are used to inform users and push developers to update their code.

@kelson42 Do you mean compile-time warnings or run-time warnings?

**Comment by kelson42** [comment]
@veloman-yunkan I thinf compile time is enough, such a system has already been implmented in libzim AFAIK.

**Comment by mgautierfr** [comment]
Compile time yes.
And in fact is is already implemented in libkiwix https://github.com/kiwix/libkiwix/blob/master/include/common.h#L7-L14
We must pass on the API and mark the newly deprecated methods as deprecated.

I also wonder if we should remove the already deprecated methods. It's been a long time since they are deprecated, it makes sense to remove them.

**Comment by mgautierfr** [comment]
@veloman-yunkan Are you working on that or I do it ?

**Comment by veloman-yunkan** [comment]
@mgautierfr I haven't really done anything significant to claim that I am working on this, so if you want to take it over - you are welcome!
