### ISSUE TITLE
Option to sort libraries shown on kiwix-serve

### ISSUE THREAD

**Issue by Shdwdrgn** [kiwix/libkiwix#752]
When viewing the library of zim files on the kiwix-serve home page, the files have no apparent order to them (either by title, filename, age of the zim file, or the order the files were added to library.xml).

Could we add options to control the order of the zim files?  There are a few different options that should cover most people's requirements:
- Sort alphabetically by title
- Sort alphabetically by filename
- List by the order the zim files were added to library.xml
- Allow a config file which lists each zim filename, in the order the admin would like them listed

And going one step further, it could also be helpful to have options for the number of columns, and whether to organize the list down then across, or across then down.

At the very least, it would be nice to have the list sorted by title as the default.  If you have several zim files downloaded then this feature would group the similar content, for example all of the wiki* libraries would be organized together.

**Comment by kelson42** [comment]
@Shdwdrgn I think we should start from concrete examples. Would you be able please to give three simple and realistic scenarios which don't deliver what you expected (details about what you expected each time are welcome).

**Comment by Shdwdrgn** [comment]
Correct... either to be able to define the order specifically, or to have them sorted by some easily-identifiable method like the title shown on the web page or the filename so that the outcome is more predictable.

**Comment by kelson42** [comment]
@Shdwdrgn Thx for clarifying your request. This is a feature request that you are not alone to ask for. This is pretty specific and as long as we didn't had proper filters, this kind of feature request was not high prioritised. This seems legitim and I believe we could/should do something in one of the next milestones.

That said, we still need to discuss the "how". This other ticket requests improvements around books sorting: #702.

At this stage, I don't really have an opinion about the fact of inserting a visual way in kiwix-serve to specify the order. But that does not way there is not a way (via the URL for example) to specify it. Anyway, this is not really what is requested here.

Specifying the order directly based on the order in the XML file seems odd and not a good approach (because far too implicit).

Maybe we should just create a new attribute `order` in the XML?

**Comment by Shdwdrgn** [comment]
From what I can tell of the other ticket, that request seems to be looking for a way for users to sort the content, while I am looking for a sorting option on the administrative side.  However I can certainly see the advantage of merging both of these requests together so an admin could set the default sorting, but then users could select other options.

I agree that simply setting the order based on how each entry appears in the xml file is a bit 'clunky' but thought that could be the fastest way to modify the code so that admins could manage it.  Adding an 'order' attribute to each 'book' tag would allow for more direct management though and be easier to work with if someone created their own editor.  Or even a general 'sort' attribute under the 'library' tag to specify sorting by path, title, or name would be useful.

**Comment by kelson42** [comment]
I will close the ticket as I have a strong will to not complexify much the UI. I still understand that the admin of a kiwix-serve might want to propose content in a certain order, but now that we have multiple filter it will be difficult to garanty it. For the rest, the future popularity property will be take in account to sort the content, so it should be used and abused to force the sorting.
