### ISSUE TITLE
Unoptimal fulltext search link in 404 page

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#793]
Steps:
* Go to https://library.kiwix.org/wikipedia_fr_all_maxi_2022-04/A/Albert_Einsteind (URL is on purpose wrong, with surnumerous trailing `d`)
* 404 page is displayed properly with an invitation to make a fulltext search
* Fulltext search link is https://library.kiwix.org/search?content=wikipedia_fr_all_maxi_2022-04&pattern=Albert_Einsteind, which is not good because even https://library.kiwix.org/search?content=wikipedia_fr_all_maxi_2022-04&pattern=Albert_Einstein (so with the proper writting gives no result)

Cause:
* We take the part to search from the last part of URL wich seems good. But the `_` character makes things breaking.

Proposal:
* Either remove this fulltext part of the error message
* Or replace usual separators with a space, like `_` or `-`

**Comment by veloman-yunkan** [comment]
I am against making the search suggestion smart and I think that keeping it in its current form still makes sense.

The heuristics you propose makes sense for Wikipedia but not for some other websites. For example, on [cppreference.com](https://cppreference.com) underscores are first-class characters rather than whitespace replacements (e.g. https://en.cppreference.com/w/cpp/string/basic_string). Besides trying to extract the intended terms from a wrong URL will have to deal with a broader spectrum of challenges:

- https://library.kiwix.org/wikipedia_fr_all_maxi_2022-04/Albert/Einstein
- https://library.kiwix.org/wikipedia_fr_all_maxi_2022-04/Albert_Einstein/ (probably it makes sense to improve handling of this case because the current behaviour doesn't make any sense)
- https://library.kiwix.org/wikipedia_fr_all_maxi_2022-04/Einstein,_Albert
- https://library.kiwix.org/wikipedia_fr_all_maxi_2022-04/I/Albert_Einstein_at_the_age_of_three_(1882).jpgg 

If this becomes a real nuisance that a lot of users want to be solved, then probably the conversion of wrong URLs to search suggestions should be delegated to the ZIM file, i.e. the ZIM file must define in some way how a given URL must be transformed to a search.

**Comment by kelson42** [comment]
@veloman-yunkan Agree, my idea is probably not the best one indeed. Closing for the moment.
