### ISSUE TITLE
wikiHow homepage is not loading due to wrong url return from library.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/libkiwix#824]
## Description

Android OS: 11
Device: Redmi Note 9
Zim File: wikiHow

### With Libkiwix  10.1.1

* Main Page url comes from zimReader: mainPage
* Url comes from WebView: https://kiwix.app/mainPage.
* is redirected url comes from zim reader true
* redirect url comes from zim reader https://kiwix.app/

### With Libkiwix 9.4.1
* its working fine.
* Main Page url comes from zimReader: W/mainPage
* Url comes from WebView:  https://kiwix.app/W/mainPage
* redirect url comes from zim reader: https://kiwix.app/C/대문

### Video

https://user-images.githubusercontent.com/34593983/192718951-fb585923-e6bb-4bfb-b6e5-dfb0cf06bb23.mp4

**Comment by kelson42** [comment]
@MohitMaliFtechiz This is a bug report for android. Here we are interested in what do you do at libkiwix level? Which primitive do you call and what do you get as a value and what you expect?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

We are calling Method to get main Page url inside ```JNIKiwixReader``` class ```public native String checkUrl(String url);``` . We are expecting value  [https://kiwix.app/C/대문](https://kiwix.app/C/%EB%8C%80%EB%AC%B8) while receiving  https://kiwix.app/ on 10.1.1. For older version 9.4.1 url returning is correct.

**Comment by mgautierfr** [comment]
@MohitMaliFtechiz 
This issue is related to the change in libzim API (and so libkwix api).
On "old" zim files, the main entry, returned by libzim is directly the actual main entry.
This is somehow problematic as when you ask for entry path "/" (main page), you may have a entry for path "foo/index.html". As all links are relatives, the link in the page are relative to "foo/index.html", but the application thinks the base is "/". So all links are broken. All application's developers must know about this and check the path of the entry returned and do a redirection themselves if they are loading main page.
To avoid that, new zim files now have a redirection entry as main page (redirecting to the actual main page). So the "main" page is always a "mainPage" (url) entry and is always a redirection (to the entry "foo/index.html" in our exemple). This make the redirection explicit.

The problem here is that the jni wrapper has not been update. (https://github.com/kiwix/libkiwix/blob/10.1.1/src/wrapper/java/kiwixreader.cpp#L123-L137) (Have point the old code in libkiwix, but it is the same with the wrapper in java-libkiwix).
`JNIKiwixReader_getMainPage` get the path of the main entry and doesn't check the entry is a redirection or not.
It can be easily fixed by getting the final entry:
```cpp
std::string cUrl = READER->getMainPage().getFinalEntry().getPath();
```

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr ,

Thank you for suggestion , I can see homepage now but found another issue will post them on separate ticket.
