### ISSUE TITLE
.so file missing in release tar for linux architecture.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/libkiwix#845]
Tar uploaded at https://download.kiwix.org/release/libkiwix/ for linux architecture missing .so file that is required for running test at java-libkiwix.

**Comment by kelson42** [comment]
I confirm, this is missing!!!

**Comment by mgautierfr** [comment]
This is surprising. 

But it should be fixed with commit https://github.com/kiwix/kiwix-build/pull/548/commits/0226d7a24fd10c065a9519e5a3f3a729cc3abe61 on kiwix/kiwix-build#548
(At least I will check that with kiwix/kiwix-build#548)

**Comment by mgautierfr** [comment]
> Tar uploaded at [download.kiwix.org/release/libkiwix](https://download.kiwix.org/release/libkiwix/) for linux architecture missing .so file that is required for running test at java-libkiwix.

Do you really need the linux architecture ? You should better use the android architecture no ?

A proper publication of libkiwix should use a "mixed" build (dependencies build statically and libkiwix build dynamically).
But libkiwix doesn't compile currently in mixed form on linux. The publication of this archive is a bug in the kiwix-build process where it build libkiwix statically. This wrong publication has been introduced when adding the publication of libkiwix for android.
I think we should simply remove it (at least for now)

**Comment by kelson42** [comment]
> > Tar uploaded at [download.kiwix.org/release/libkiwix](https://download.kiwix.org/release/libkiwix/) for linux architecture missing .so file that is required for running test at java-libkiwix.
> 
> Do you really need the linux architecture ? You should better use the android architecture no ?

Here my feedback as I'm the one to push this.

First this is `java-libkiwix`, not `android-libkiwix`, so even if this is true that our usage of the moment is on Android, I think it would be a bad approach to not include `x86_64` in it.

Then, there is the current question of the unit and automated testing of the `java-libkiwix` ; if we test one of the Android binding then we will have to run the unit tests. the code coverage, ... in an emulator. This is not something I want because it add an unecessary layer of emulation which is going to slow down and probably even fragilize the whole CI. Therefore, it is preferable to test it natively on `x86_64`/

**Comment by mgautierfr** [comment]
Ok. I will remove thing related to this issue on https://github.com/kiwix/kiwix-build/pull/548 and fix this is another PR
