### ISSUE TITLE
Handling of language variants by kiwix-serve

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#858]
As requested by https://github.com/kiwix/libkiwix/pull/849#issuecomment-1342666682

**Comment by kelson42** [comment]
@veloman-yunkan I understand. I don't want us to invest a lot of resources on this. I just want to secure that if someone has `fr-CH` or `pt-PT`, we properly deliver `fr` or `pt` in worse scenario. If you have an extract of the specification around this explicitly saying that `fr` has to be send as part of the HTTP request header, if `fr-CH` is chosen by the browser user. Then fine to me, otherwise I would really prefer to explicitly handle the case on our side.

**Comment by kelson42** [comment]
After discussion IRL with @mgautierfr and @veloman-yunkan it looks like the current behaviour is already the good one.
