### ISSUE TITLE
Ability to toggle magnet support?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#938]
Our download modal offers magnet links if an URL similar to ZIM download URL with `.magnet` suffix exists

https://github.com/kiwix/libkiwix/blob/1a92d4a0b5b6be51fdaff719ff0152a807ba71cc/static/skin/index.js#L200-L214

It is understood that the sole* use case for this is library.kiwix.org but [Our magnet links are broken](https://github.com/kiwix/container-images/issues/242), and we can't really fix them.

Additionally, there aren't much client for those magnets

I didn't look for torrent client but [this list on WP](https://en.wikipedia.org/wiki/Magnet_URI_scheme#Clients) is not reassuring. For our webseed-magnet to work, we'd need the client to support HTTP `xr` or `as` (and `tr` for regular transfers). In that list, it means:
- gtk-gnutella: windows, linux
- limewire: dead
- shareaza: windows only
- tixati: proprietary, windows/linux
- vuze: properietary (and heavy)

To me, it sounds like most users would use another client and get a never-starting download… leading them to think it's a peer issue (they have no idea about the webseed) thus leading them to the direct link. Create a vicious circle with less BT users, reinforcing itself.

**Comment by mgautierfr** [comment]
Another solution would be to remove magnet links from `library.kiwix.org` ?

**Comment by rgaudin** [comment]
Sure but It's automatically provided by mirrorbrain as `.magnet` and `?magnet`. It doesn't look like it can be disabled ([doc](https://mirrorbrain-docs.readthedocs.io/en/latest/configuration.html#magnet-links)).

We could hack a hack on the reverse proxy to return a blank payload on every `.magnet$` request though…

**Comment by rgaudin** [comment]
Let's add a hack in libkiwix's index.js for now to fix the magnet.

**Comment by kelson42** [comment]
@rgaudin I would like to revive this ticket as it seems relatively important as well as relatively easy to fix. I understand that we are mostly "stuck" here because of the deprecation of `poeml/mirrorbrain` and our lack of strategy and resources to deal with this challenge.

I believe that this bug could be fixed both by patching Mirrorbrain OR by patching/hacking our kiwix-serve Javascript. Both are OK to me and I believe we should do it ASAP (this is why I have put this ticket in the `13.0.0` milestone at the last moment).

More generaly, I think we are not ready yet to switch to an alternative to Mirrorbrain and I'm not even sure this would be a good thing to do at all (not really sure the few alternative are good enough). Considering that we have a few other issues related to Mirrorbain, maybe we could confortable a few additional years by just forking and fixing our few things?

Would that not be an appropriate path to:
* Fork Mirrorbain
* Make a patch to Mirrorbrain
* Propose a PR upstream (and see what happens)

**Comment by rgaudin** [comment]
I'm concerned by your recurrent dismissal of mirrorbrain alternatives because there has never been any argument to support it. “others are probably not as good” is an acceptable intuition but that's it.

[mirrobits](https://github.com/etix/mirrorbits) looks really solid and the fact that VLC has been using it for close to 10y supports it.

Switching to it seems relatively straightforward. I'd like to recall that those tools are purely server-side, on our end. Migrating would not imply anything on the mirrors. We could have both run in parallel and switch once we're ready.

The only drawback I see is that mirrorbits (as all other alt.) doesn't support torrent at all. I imagine they consider it a different topic. We could generate those.

I don't think investing time in forking/fixing mirrorbrain would be a good move. I'd prefer directing our resources towards something more sustainable.

Anyway, this is all related to the root cause (which we can live with) and not this ticket. Regarding this very ticket, I am still in favor of disabling magnets because the audience is small.
Should it be considered important, I'd support a kiwix-serve JS hack: easy to implement and that's where it matters.

**Comment by kelson42** [comment]
> Anyway, this is all related to the root cause (which we can live with) and not this ticket. Regarding this very ticket, I am still in favor of disabling magnets because the audience is small.

I don't feel ready to give up on this: magnet links are elegant way to share content in a decentralised way

> Should it be considered important, I'd support a kiwix-serve JS hack: easy to implement and that's where it matters.

I would really prefer we do that.

**Comment by rgaudin** [comment]
> magnet links are elegant way to share content in a decentralised way

Absolutely but as indicated in the ticket, we seed magnet are poorly supported. That's why I' saying the audience is small. Also, it's not much decentralized in web seed only. But having our super seeder (as mentioned in the ticket) would solve both and turn this into a more useful feature.


Let me know if you want me to work on the JS hack. I don't know who maintains the JS reader in lib kiwix
